on:
  -push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses:actions/checkout@v3
      - name: Escribir texto
        run: |
          echo Este texto se escribe al ejecutar el workflow
          echo Podria haber mas de una linea
